//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientSOPApp1.MySerivice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MySerivice.MyServiceClassSoap")]
    public interface MyServiceClassSoap {
        
        // CODEGEN: Generating message contract since message SayHelloRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SayHello", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClientSOPApp1.MySerivice.SayHelloResponse SayHello(ClientSOPApp1.MySerivice.SayHelloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SayHello", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientSOPApp1.MySerivice.SayHelloResponse> SayHelloAsync(ClientSOPApp1.MySerivice.SayHelloRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("userName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SayHello", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SayHelloRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public ClientSOPApp1.MySerivice.UserDetails UserDetails;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userName;
        
        public SayHelloRequest() {
        }
        
        public SayHelloRequest(ClientSOPApp1.MySerivice.UserDetails UserDetails, string userName) {
            this.UserDetails = UserDetails;
            this.userName = userName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SayHelloResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SayHelloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string SayHelloResult;
        
        public SayHelloResponse() {
        }
        
        public SayHelloResponse(string SayHelloResult) {
            this.SayHelloResult = SayHelloResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyServiceClassSoapChannel : ClientSOPApp1.MySerivice.MyServiceClassSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyServiceClassSoapClient : System.ServiceModel.ClientBase<ClientSOPApp1.MySerivice.MyServiceClassSoap>, ClientSOPApp1.MySerivice.MyServiceClassSoap {
        
        public MyServiceClassSoapClient() {
        }
        
        public MyServiceClassSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyServiceClassSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceClassSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceClassSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientSOPApp1.MySerivice.SayHelloResponse ClientSOPApp1.MySerivice.MyServiceClassSoap.SayHello(ClientSOPApp1.MySerivice.SayHelloRequest request) {
            return base.Channel.SayHello(request);
        }
        
        public string SayHello(ClientSOPApp1.MySerivice.UserDetails UserDetails, string userName) {
            ClientSOPApp1.MySerivice.SayHelloRequest inValue = new ClientSOPApp1.MySerivice.SayHelloRequest();
            inValue.UserDetails = UserDetails;
            inValue.userName = userName;
            ClientSOPApp1.MySerivice.SayHelloResponse retVal = ((ClientSOPApp1.MySerivice.MyServiceClassSoap)(this)).SayHello(inValue);
            return retVal.SayHelloResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientSOPApp1.MySerivice.SayHelloResponse> ClientSOPApp1.MySerivice.MyServiceClassSoap.SayHelloAsync(ClientSOPApp1.MySerivice.SayHelloRequest request) {
            return base.Channel.SayHelloAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientSOPApp1.MySerivice.SayHelloResponse> SayHelloAsync(ClientSOPApp1.MySerivice.UserDetails UserDetails, string userName) {
            ClientSOPApp1.MySerivice.SayHelloRequest inValue = new ClientSOPApp1.MySerivice.SayHelloRequest();
            inValue.UserDetails = UserDetails;
            inValue.userName = userName;
            return ((ClientSOPApp1.MySerivice.MyServiceClassSoap)(this)).SayHelloAsync(inValue);
        }
    }
}
